// Product catalog for Best Supply.
// Replace affiliateUrl values with your own affiliate links before deploying.
// price is optional; the current UI does not require it, but it is useful for future cards/admin views.

export const products = [
  {
    "id": "apple-studio-display",
    "name": "Studio Display",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.apple.com/shop/buy-mac/apple-studio-display",
    "price": "$1,599",
    "startingVotes": 980
  },
  {
    "id": "grams28-151-stealth-backpack",
    "name": "151 Stealth Backpack",
    "brand": "Grams28",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Grams28.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.grams28.com/products/151-stealth-backpack",
    "price": "$889",
    "startingVotes": 973
  },
  {
    "id": "herman-miller-aeron",
    "name": "Aeron",
    "brand": "Herman Miller",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Herman Miller.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://store.hermanmiller.com/office-chairs-aeron/aeron-chair/2195348.html",
    "price": "$1,930",
    "startingVotes": 966
  },
  {
    "id": "fellow-stagg-ekg-electric-kettle",
    "name": "Stagg EKG Electric Kettle",
    "brand": "Fellow",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Fellow.",
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://fellowproducts.com/products/stagg-ekg-electric-kettle",
    "price": "$200",
    "startingVotes": 959
  },
  {
    "id": "porsche-911-turbo-s",
    "name": "911 Turbo S",
    "brand": "Porsche",
    "category": "Vehicles",
    "tag": "Curated pick",
    "description": "A design-led vehicles pick from Porsche.",
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.porsche.com/usa/models/911/911-turbo-models/911-turbo-s/",
    "price": "$270,000",
    "startingVotes": 952
  },
  {
    "id": "omega-speedmaster",
    "name": "Speedmaster",
    "brand": "Omega",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Omega.",
    "image": "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.omegawatches.com/en-us/watches/speedmaster",
    "price": "$7,800",
    "startingVotes": 945
  },
  {
    "id": "phaidon-dieter-rams-the-complete-works",
    "name": "Dieter Rams: The Complete Works",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.phaidon.com/store/design/dieter-rams-the-complete-works-9781838669095/",
    "price": "$59",
    "startingVotes": 938
  },
  {
    "id": "taschen-virgil-abloh-nike-icons",
    "name": "Virgil Abloh. Nike. ICONS",
    "brand": "Taschen",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Taschen.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.taschen.com/en/books/fashion/04687/virgil-abloh-nike-icons/",
    "price": "$59",
    "startingVotes": 931
  },
  {
    "id": "lego-icons-10295-porsche-911",
    "name": "Icons 10295 Porsche 911",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/product/porsche-911-10295",
    "price": "$170",
    "startingVotes": 924
  },
  {
    "id": "work-louder-k-no-b-1",
    "name": "k•no•b•1",
    "brand": "Work Louder",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Work Louder.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://worklouder.cc/products/knob-1",
    "price": "$439",
    "startingVotes": 917
  },
  {
    "id": "nothing-phone-4a-pro",
    "name": "Phone (4a) Pro",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://nothing.tech/products/phone-3a-pro",
    "price": "$500",
    "startingVotes": 910
  },
  {
    "id": "sigma-bf",
    "name": "BF",
    "brand": "Sigma",
    "category": "Cameras",
    "tag": "Curated pick",
    "description": "A design-led cameras pick from Sigma.",
    "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.sigmaphoto.com/cameras/bf-camera",
    "price": "$2,199",
    "startingVotes": 903
  },
  {
    "id": "rolex-datejust",
    "name": "Datejust",
    "brand": "Rolex",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Rolex.",
    "image": "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.rolex.com/watches/datejust",
    "price": "$10,000",
    "startingVotes": 896
  },
  {
    "id": "goyard-saint-florentin-wallet",
    "name": "Saint-Florentin Wallet",
    "brand": "Goyard",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Goyard.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.goyard.com/us_en/portefeuille-saint-florentin.html",
    "price": "$1,500",
    "startingVotes": 889
  },
  {
    "id": "nomad-base-one-max-3-in-1",
    "name": "Base One Max 3-in-1",
    "brand": "Nomad",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Nomad.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://nomadgoods.com/products/base-one-max-3-in-1",
    "price": "$149",
    "startingVotes": 882
  },
  {
    "id": "lofree-flow-2",
    "name": "Flow 2",
    "brand": "Lofree",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Lofree.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lofree.co/products/flow-2",
    "price": "$189",
    "startingVotes": 875
  },
  {
    "id": "apple-iphone-air",
    "name": "iPhone Air",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.apple.com/iphone/",
    "price": "$999",
    "startingVotes": 868
  },
  {
    "id": "nothing-headphones-1",
    "name": "Headphones (1)",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://nothing.tech/products/headphone-1",
    "price": "$299",
    "startingVotes": 861
  },
  {
    "id": "kismas-doric-lamp-01",
    "name": "Doric Lamp 01",
    "brand": "Kismas",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Kismas.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://kismas.co/products/doric-lamp-01",
    "price": "$169",
    "startingVotes": 854
  },
  {
    "id": "leica-leica-q3",
    "name": "Leica Q3",
    "brand": "Leica",
    "category": "Cameras",
    "tag": "Curated pick",
    "description": "A design-led cameras pick from Leica.",
    "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://leica-camera.com/en-US/photography/cameras/q/q3-black",
    "price": "$6,735",
    "startingVotes": 847
  },
  {
    "id": "rimowa-classic-cabin",
    "name": "Classic Cabin",
    "brand": "Rimowa",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Rimowa.",
    "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.rimowa.com/us/en/luggage/colour/silver/cabin/97353004.html",
    "price": "$1,600",
    "startingVotes": 840
  },
  {
    "id": "humans-since-1982-clockclock-24",
    "name": "ClockClock 24",
    "brand": "Humans Since 1982",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Humans Since 1982.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.humanssince1982.com/clockclock-24",
    "price": "$8,500",
    "startingVotes": 833
  },
  {
    "id": "crushgrind-p-1-pepper-mill",
    "name": "P–1 Pepper Mill",
    "brand": "CrushGrind",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from CrushGrind.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.crushgrind.com/products/p-1-pepper-mill",
    "price": "$299",
    "startingVotes": 826
  },
  {
    "id": "b-ng-l-p-small-square-in-orange-acrylic",
    "name": "Lớp small square in orange acrylic",
    "brand": "BằNG",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from BằNG.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.bang-studio.com/",
    "price": "$195",
    "startingVotes": 819
  },
  {
    "id": "herman-miller-noguchi-coffee-table",
    "name": "Noguchi Coffee Table",
    "brand": "Herman Miller",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Herman Miller.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://store.hermanmiller.com/living-room-furniture-side-tables/noguchi-table/100104469.html",
    "price": "$2,745",
    "startingVotes": 812
  },
  {
    "id": "breda-pulse-tandem",
    "name": "Pulse (Tandem)",
    "brand": "Breda",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Breda.",
    "image": "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.breda.com/products/pulse-tandem",
    "price": "$230",
    "startingVotes": 805
  },
  {
    "id": "nothing-ear-3",
    "name": "Ear (3)",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://nothing.tech/products/ear-3",
    "price": "$149",
    "startingVotes": 798
  },
  {
    "id": "aulumu-m01-4-in-1-folding-wireless-charging-station-pad",
    "name": "M01 4-in-1 Folding Wireless Charging Station & Pad",
    "brand": "Aulumu",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Aulumu.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://aulumu.com/products/m01-4-in-1-folding-wireless-charging-station-pad",
    "price": "$109",
    "startingVotes": 791
  },
  {
    "id": "la-marzocco-linea-micra",
    "name": "Linea Micra",
    "brand": "La Marzocco",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from La Marzocco.",
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://lamarzocco.com/us/en/home-products/espresso-machines/linea-micra/",
    "price": "$4,500",
    "startingVotes": 784
  },
  {
    "id": "subminimal-subscale",
    "name": "Subscale",
    "brand": "Subminimal",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Subminimal.",
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://subminimal.com/products/subscale",
    "price": "$50",
    "startingVotes": 777
  },
  {
    "id": "sony-wh-1000-xm6",
    "name": "WH-1000 XM6",
    "brand": "Sony",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Sony.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://electronics.sony.com/audio/headphones/headband/p/wh1000xm6-b",
    "price": "$400",
    "startingVotes": 770
  },
  {
    "id": "nintendo-switch-2",
    "name": "Switch 2",
    "brand": "Nintendo",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Nintendo.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.nintendo.com/us/gaming-systems/switch-2/",
    "price": "$450",
    "startingVotes": 763
  },
  {
    "id": "phaidon-the-design-book",
    "name": "The Design Book",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.phaidon.com/store/design/the-design-book-9781838661433/",
    "price": "$18",
    "startingVotes": 756
  },
  {
    "id": "xbloom-xbloom-studio-coffee-machine",
    "name": "xBloom Studio Coffee Machine",
    "brand": "xBloom",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from xBloom.",
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://xbloom.com/products/xbloom-studio",
    "price": "$599",
    "startingVotes": 749
  },
  {
    "id": "apple-iphone-17-pro",
    "name": "iPhone 17 Pro",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.apple.com/iphone/",
    "price": "$1,099",
    "startingVotes": 742
  },
  {
    "id": "serica-ref-1174-1-parade",
    "name": "Ref. 1174-1 Parade",
    "brand": "Serica",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Serica.",
    "image": "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.serica-watches.com/en/product/1174-parade/",
    "price": "$1,490",
    "startingVotes": 735
  },
  {
    "id": "ligne-roset-togo-loveseat",
    "name": "Togo ® Loveseat",
    "brand": "Ligne Roset",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Ligne Roset.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.ligne-roset.com/us/modele/living/sofas/togo/2602",
    "price": "$6,575",
    "startingVotes": 728
  },
  {
    "id": "dyson-solarcycle-morph-floor",
    "name": "Solarcycle Morph Floor",
    "brand": "Dyson",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Dyson.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.dyson.com/lighting/floor-lamps/solarcycle-morph",
    "price": "$849",
    "startingVotes": 721
  },
  {
    "id": "grau-salt",
    "name": "Salt",
    "brand": "Grau",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Grau.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.grau.art/en/products/salt",
    "price": "$503",
    "startingVotes": 714
  },
  {
    "id": "jbl-flip-6-portable-bluetooth-speaker",
    "name": "Flip 6 Portable Bluetooth Speaker",
    "brand": "JBL",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from JBL.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.jbl.com/bluetooth-speakers/JBLFLIP6BLKAM.html",
    "price": "$130",
    "startingVotes": 707
  },
  {
    "id": "snow-peak-titanium-spork",
    "name": "Titanium Spork",
    "brand": "Snow Peak",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Snow Peak.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.snowpeak.com/products/titanium-spork",
    "price": "$10",
    "startingVotes": 700
  },
  {
    "id": "standards-manual-parks-united-states-national-park-service-maps",
    "name": "Parks: United States National Park Service Maps",
    "brand": "Standards Manual",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Standards Manual.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://standardsmanual.com/products/parks",
    "price": "$40",
    "startingVotes": 693
  },
  {
    "id": "hoto-camplight-rechargeable-led-camping-lantern",
    "name": "CampLight Rechargeable LED Camping Lantern",
    "brand": "Hoto",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Hoto.",
    "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://hototools.com/products/camplight-rechargeable-led-camping-lantern",
    "price": "$60",
    "startingVotes": 686
  },
  {
    "id": "anker-solix-everfrost-2-electric-cooler",
    "name": "SOLIX EverFrost 2 Electric Cooler",
    "brand": "Anker",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Anker.",
    "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.anker.com/products/a17b3",
    "price": "$700",
    "startingVotes": 679
  },
  {
    "id": "snow-peak-rechargeable-mini-hozuki-lantern",
    "name": "Rechargeable Mini Hozuki Lantern",
    "brand": "Snow Peak",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Snow Peak.",
    "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.snowpeak.com/products/rechargeable-mini-hozuki",
    "price": "$70",
    "startingVotes": 672
  },
  {
    "id": "wacaco-minipresso-gr2-espresso-machine",
    "name": "Minipresso GR2 Espresso Machine",
    "brand": "Wacaco",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Wacaco.",
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.wacaco.com/products/minipresso-gr2",
    "price": "$60",
    "startingVotes": 665
  },
  {
    "id": "stelton-vacuum-jug",
    "name": "Vacuum Jug",
    "brand": "Stelton",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Stelton.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.stelton.com/en/products/em77-vacuum-jug",
    "price": "$120",
    "startingVotes": 658
  },
  {
    "id": "solo-stove-mesa-tabletop-fire-pit",
    "name": "Mesa Tabletop Fire Pit",
    "brand": "Solo Stove",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Solo Stove.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.solostove.com/en-us/p/mesa",
    "price": "$110",
    "startingVotes": 651
  },
  {
    "id": "outask-telescopic-camping-lantern",
    "name": "Telescopic Camping Lantern",
    "brand": "Outask",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Outask.",
    "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://outask-td.com/products/telescopic-lantern",
    "price": "$150",
    "startingVotes": 644
  },
  {
    "id": "smeg-electric-kettle",
    "name": "Electric Kettle",
    "brand": "Smeg",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Smeg.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.smeg.com/us/products/KLF03",
    "price": "$275",
    "startingVotes": 637
  },
  {
    "id": "lego-wildflower-bouquet",
    "name": "Wildflower Bouquet",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/product/wildflower-bouquet-10313",
    "price": "$60",
    "startingVotes": 630
  },
  {
    "id": "le-creuset-signature-round-dutch-oven",
    "name": "Signature Round Dutch Oven",
    "brand": "Le Creuset",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Le Creuset.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lecreuset.com/signature-round-dutch-oven/LS2501.html",
    "price": "$420",
    "startingVotes": 623
  },
  {
    "id": "gucci-bloom-eau-de-parfum",
    "name": "Bloom Eau De Parfum",
    "brand": "Gucci",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Gucci.",
    "image": "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.gucci.com/us/en/pr/beauty/fragrances/fragrances-for-women/bloom-eau-de-parfum-100ml-p-488830999990099",
    "price": "$60",
    "startingVotes": 616
  },
  {
    "id": "aesop-r-zu-eau-de-parfum",
    "name": "Rōzu Eau De Parfum",
    "brand": "Aesop",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Aesop.",
    "image": "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.aesop.com/us/p/fragrance/floral/rozu-eau-de-parfum/",
    "price": "$200",
    "startingVotes": 609
  },
  {
    "id": "assouline-mother-and-child-coffee-table-book",
    "name": "Mother And Child Coffee Table Book",
    "brand": "Assouline",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Assouline.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.assouline.com/products/mother-and-child",
    "price": "$120",
    "startingVotes": 602
  },
  {
    "id": "phaidon-woman-made-great-women-designers",
    "name": "Woman Made: Great Women Designers",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.phaidon.com/store/design/woman-made-great-women-designers-9781838662850/",
    "price": "$60",
    "startingVotes": 595
  },
  {
    "id": "hatch-restore-3-sunrise-alarm-clock",
    "name": "Restore 3 Sunrise Alarm Clock",
    "brand": "Hatch",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Hatch.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.hatch.co/restore",
    "price": "$170",
    "startingVotes": 588
  },
  {
    "id": "stakt-original-foldable-yoga-mat",
    "name": "Original Foldable Yoga Mat",
    "brand": "Stakt",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Stakt.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://staktmat.com/products/the-stakt-mat",
    "price": "$90",
    "startingVotes": 581
  },
  {
    "id": "gucci-mercato-tote-bag",
    "name": "Mercato Tote Bag",
    "brand": "Gucci",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Gucci.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.gucci.com/us/en/pr/women/handbags/tote-bags-for-women/mercato-tote-bag-p-815452AAC7L1060",
    "price": "$3,600",
    "startingVotes": 574
  },
  {
    "id": "kate-mcleod-sleep-stone-solid-body-moisturizer-starter-kit",
    "name": "Sleep Stone Solid Body Moisturizer Starter Kit",
    "brand": "Kate McLeod",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Kate McLeod.",
    "image": "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.katemcleod.com/products/sleep-stone",
    "price": "$45",
    "startingVotes": 567
  },
  {
    "id": "diptyque-baies-scented-candle",
    "name": "Baies Scented Candle",
    "brand": "Diptyque",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Diptyque.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.diptyqueparis.com/en_us/p/baies-berries-candle.html",
    "price": "$70",
    "startingVotes": 560
  },
  {
    "id": "spigen-classic-ls-magfit-case",
    "name": "Classic LS MagFit Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.spigen.com/products/iphone-classic-ls-magfit-case",
    "price": "$35",
    "startingVotes": 553
  },
  {
    "id": "wokyis-retro-docking-station-for-mac-mini",
    "name": "Retro Docking Station For Mac Mini",
    "brand": "Wokyis",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Wokyis.",
    "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://wokyis.com/products/retro-docking-station-for-mac-mini",
    "price": "$170",
    "startingVotes": 546
  },
  {
    "id": "spigen-classic-c1-apple-watch-charger-stand",
    "name": "Classic C1 Apple Watch Charger Stand",
    "brand": "Spigen",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Spigen.",
    "image": "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.spigen.com/products/apple-watch-classic-c1-stand",
    "price": "$20",
    "startingVotes": 539
  },
  {
    "id": "8bitdo-retro-mechanical-keyboard",
    "name": "Retro Mechanical Keyboard",
    "brand": "8BitDo",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from 8BitDo.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.8bitdo.com/retro-mechanical-keyboard/",
    "price": "$90",
    "startingVotes": 532
  },
  {
    "id": "8bitdo-retro-r8-mouse",
    "name": "Retro R8 Mouse",
    "brand": "8BitDo",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from 8BitDo.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.8bitdo.com/retro-r8-mouse/",
    "price": "$50",
    "startingVotes": 525
  },
  {
    "id": "spigen-classic-c1-magfit-case",
    "name": "Classic C1 MagFit Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.spigen.com/products/iphone-classic-c1-magfit-case",
    "price": "$35",
    "startingVotes": 518
  },
  {
    "id": "spigen-classic-ls-airpods-pro-3-case",
    "name": "Classic LS AirPods Pro 3 Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.spigen.com/products/airpods-pro-classic-ls-case",
    "price": "$45",
    "startingVotes": 511
  },
  {
    "id": "native-union-pop-phone",
    "name": "Pop Phone",
    "brand": "Native Union",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Native Union.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.nativeunion.com/products/pop-phone",
    "price": "$40",
    "startingVotes": 504
  },
  {
    "id": "foreverspin-stainless-steel-spinning-top",
    "name": "Stainless Steel Spinning Top",
    "brand": "ForeverSpin",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from ForeverSpin.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://foreverspin.com/products/stainless-steel-spinning-top",
    "price": "$47",
    "startingVotes": 497
  },
  {
    "id": "lego-ferrari-f40-10248",
    "name": "Ferrari F40 10248",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/search?q=Ferrari%20F40",
    "price": "$25",
    "startingVotes": 490
  },
  {
    "id": "printworks-art-of-chess-set",
    "name": "Art of Chess Set",
    "brand": "Printworks",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Printworks.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://printworksmarket.com/products/art-of-chess",
    "price": "$60",
    "startingVotes": 483
  },
  {
    "id": "the-serious-toy-company-tyrannosaurus",
    "name": "Tyrannosaurus",
    "brand": "The Serious Toy Company",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from The Serious Toy Company.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://theserioustoycompany.com/",
    "price": "$60",
    "startingVotes": 476
  },
  {
    "id": "lego-fifa-world-cup-official-trophy",
    "name": "FIFA World Cup Official Trophy",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/product/fifa-world-cup-official-trophy-43020",
    "price": "$200",
    "startingVotes": 469
  },
  {
    "id": "lego-game-boy-72046",
    "name": "Game Boy™ 72046",
    "brand": "Lego",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Lego.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/product/game-boy-72046",
    "price": "$60",
    "startingVotes": 462
  },
  {
    "id": "cards-against-humanity-international-edition",
    "name": "International Edition",
    "brand": "Cards Against Humanity",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Cards Against Humanity.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.cardsagainsthumanity.com/products/cards-against-humanity-international-edition",
    "price": "$30",
    "startingVotes": 455
  },
  {
    "id": "theory-11-artisan-playing-cards",
    "name": "Artisan Playing Cards",
    "brand": "Theory 11",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Theory 11.",
    "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://store.theory11.com/products/artisan",
    "price": "$20",
    "startingVotes": 448
  },
  {
    "id": "lego-icons-land-rover-classic-defender-90",
    "name": "Icons Land Rover Classic Defender 90",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
    "affiliateUrl": "https://www.lego.com/en-us/product/land-rover-classic-defender-90-10317",
    "price": "$240",
    "startingVotes": 441
  }
];
