// Product catalog for Best Supply.
// Use only product images you have rights to use: your own photos, merchant/affiliate-feed images, or images explicitly licensed for your site.
// Do not hotlink/copy images from other curated directories. Add licensed image URLs in the image field.
// price is shown beside the Buy button. Replace affiliateUrl values with your own affiliate links.
// Images are resolved from official product pages first, then Amazon, then eBay via /api/product-image.
// For best results, replace amazonUrl/ebayUrl with exact affiliate product-page URLs instead of search URLs.

export const products = [
  {
    "id": "apple-studio-display",
    "name": "Studio Display",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "",
    "affiliateUrl": "https://www.apple.com/shop/buy-mac/apple-studio-display",
    "amazonUrl": "https://www.amazon.com/s?k=Apple+Studio+Display",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Apple+Studio+Display",
    "price": "$1,599",
    "startingVotes": 980
  },
  {
    "id": "grams28-151-stealth-backpack",
    "name": "151 Stealth Backpack",
    "brand": "Grams28",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Grams28.",
    "image": "",
    "affiliateUrl": "https://www.grams28.com/products/151-stealth-backpack",
    "amazonUrl": "https://www.amazon.com/s?k=Grams28+151+Stealth+Backpack",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Grams28+151+Stealth+Backpack",
    "price": "$889",
    "startingVotes": 973
  },
  {
    "id": "herman-miller-aeron",
    "name": "Aeron",
    "brand": "Herman Miller",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Herman Miller.",
    "image": "",
    "affiliateUrl": "https://store.hermanmiller.com/office-chairs-aeron/aeron-chair/2195348.html",
    "amazonUrl": "https://www.amazon.com/s?k=Herman+Miller+Aeron",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Herman+Miller+Aeron",
    "price": "$1,930",
    "startingVotes": 966
  },
  {
    "id": "fellow-stagg-ekg-electric-kettle",
    "name": "Stagg EKG Electric Kettle",
    "brand": "Fellow",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Fellow.",
    "image": "",
    "affiliateUrl": "https://fellowproducts.com/products/stagg-ekg-electric-kettle",
    "amazonUrl": "https://www.amazon.com/s?k=Fellow+Stagg+EKG+Electric+Kettle",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Fellow+Stagg+EKG+Electric+Kettle",
    "price": "$200",
    "startingVotes": 959
  },
  {
    "id": "porsche-911-turbo-s",
    "name": "911 Turbo S",
    "brand": "Porsche",
    "category": "Vehicles",
    "tag": "Curated pick",
    "description": "A design-led vehicles pick from Porsche.",
    "image": "",
    "affiliateUrl": "https://www.porsche.com/usa/models/911/911-turbo-models/911-turbo-s/",
    "amazonUrl": "https://www.amazon.com/s?k=Porsche+911+Turbo+S",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Porsche+911+Turbo+S",
    "price": "$270,000",
    "startingVotes": 952
  },
  {
    "id": "omega-speedmaster",
    "name": "Speedmaster",
    "brand": "Omega",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Omega.",
    "image": "",
    "affiliateUrl": "https://www.omegawatches.com/en-us/watches/speedmaster",
    "amazonUrl": "https://www.amazon.com/s?k=Omega+Speedmaster",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Omega+Speedmaster",
    "price": "$7,800",
    "startingVotes": 945
  },
  {
    "id": "phaidon-dieter-rams-the-complete-works",
    "name": "Dieter Rams: The Complete Works",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "",
    "affiliateUrl": "https://www.phaidon.com/store/design/dieter-rams-the-complete-works-9781838669095/",
    "amazonUrl": "https://www.amazon.com/s?k=Phaidon+Dieter+Rams%3A+The+Complete+Works",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Phaidon+Dieter+Rams%3A+The+Complete+Works",
    "price": "$59",
    "startingVotes": 938
  },
  {
    "id": "taschen-virgil-abloh-nike-icons",
    "name": "Virgil Abloh. Nike. ICONS",
    "brand": "Taschen",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Taschen.",
    "image": "",
    "affiliateUrl": "https://www.taschen.com/en/books/fashion/04687/virgil-abloh-nike-icons/",
    "amazonUrl": "https://www.amazon.com/s?k=Taschen+Virgil+Abloh.+Nike.+ICONS",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Taschen+Virgil+Abloh.+Nike.+ICONS",
    "price": "$59",
    "startingVotes": 931
  },
  {
    "id": "lego-icons-10295-porsche-911",
    "name": "Icons 10295 Porsche 911",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/product/porsche-911-10295",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+Icons+10295+Porsche+911",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+Icons+10295+Porsche+911",
    "price": "$170",
    "startingVotes": 924
  },
  {
    "id": "work-louder-k-no-b-1",
    "name": "k•no•b•1",
    "brand": "Work Louder",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Work Louder.",
    "image": "",
    "affiliateUrl": "https://worklouder.cc/products/knob-1",
    "amazonUrl": "https://www.amazon.com/s?k=Work+Louder+k%E2%80%A2no%E2%80%A2b%E2%80%A21",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Work+Louder+k%E2%80%A2no%E2%80%A2b%E2%80%A21",
    "price": "$439",
    "startingVotes": 917
  },
  {
    "id": "nothing-phone-4a-pro",
    "name": "Phone (4a) Pro",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "",
    "affiliateUrl": "https://nothing.tech/products/phone-3a-pro",
    "amazonUrl": "https://www.amazon.com/s?k=Nothing+Phone+%284a%29+Pro",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Nothing+Phone+%284a%29+Pro",
    "price": "$500",
    "startingVotes": 910
  },
  {
    "id": "sigma-bf",
    "name": "BF",
    "brand": "Sigma",
    "category": "Cameras",
    "tag": "Curated pick",
    "description": "A design-led cameras pick from Sigma.",
    "image": "",
    "affiliateUrl": "https://www.sigmaphoto.com/cameras/bf-camera",
    "amazonUrl": "https://www.amazon.com/s?k=Sigma+BF",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Sigma+BF",
    "price": "$2,199",
    "startingVotes": 903
  },
  {
    "id": "rolex-datejust",
    "name": "Datejust",
    "brand": "Rolex",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Rolex.",
    "image": "",
    "affiliateUrl": "https://www.rolex.com/watches/datejust",
    "amazonUrl": "https://www.amazon.com/s?k=Rolex+Datejust",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Rolex+Datejust",
    "price": "$10,000",
    "startingVotes": 896
  },
  {
    "id": "goyard-saint-florentin-wallet",
    "name": "Saint-Florentin Wallet",
    "brand": "Goyard",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Goyard.",
    "image": "",
    "affiliateUrl": "https://www.goyard.com/us_en/portefeuille-saint-florentin.html",
    "amazonUrl": "https://www.amazon.com/s?k=Goyard+Saint-Florentin+Wallet",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Goyard+Saint-Florentin+Wallet",
    "price": "$1,500",
    "startingVotes": 889
  },
  {
    "id": "nomad-base-one-max-3-in-1",
    "name": "Base One Max 3-in-1",
    "brand": "Nomad",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Nomad.",
    "image": "",
    "affiliateUrl": "https://nomadgoods.com/products/base-one-max-3-in-1",
    "amazonUrl": "https://www.amazon.com/s?k=Nomad+Base+One+Max+3-in-1",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Nomad+Base+One+Max+3-in-1",
    "price": "$149",
    "startingVotes": 882
  },
  {
    "id": "lofree-flow-2",
    "name": "Flow 2",
    "brand": "Lofree",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Lofree.",
    "image": "",
    "affiliateUrl": "https://www.lofree.co/products/flow-2",
    "amazonUrl": "https://www.amazon.com/s?k=Lofree+Flow+2",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lofree+Flow+2",
    "price": "$189",
    "startingVotes": 875
  },
  {
    "id": "apple-iphone-air",
    "name": "iPhone Air",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "",
    "affiliateUrl": "https://www.apple.com/iphone/",
    "amazonUrl": "https://www.amazon.com/s?k=Apple+iPhone+Air",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Apple+iPhone+Air",
    "price": "$999",
    "startingVotes": 868
  },
  {
    "id": "nothing-headphones-1",
    "name": "Headphones (1)",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "",
    "affiliateUrl": "https://nothing.tech/products/headphone-1",
    "amazonUrl": "https://www.amazon.com/s?k=Nothing+Headphones+%281%29",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Nothing+Headphones+%281%29",
    "price": "$299",
    "startingVotes": 861
  },
  {
    "id": "kismas-doric-lamp-01",
    "name": "Doric Lamp 01",
    "brand": "Kismas",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Kismas.",
    "image": "",
    "affiliateUrl": "https://kismas.co/products/doric-lamp-01",
    "amazonUrl": "https://www.amazon.com/s?k=Kismas+Doric+Lamp+01",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Kismas+Doric+Lamp+01",
    "price": "$169",
    "startingVotes": 854
  },
  {
    "id": "leica-leica-q3",
    "name": "Leica Q3",
    "brand": "Leica",
    "category": "Cameras",
    "tag": "Curated pick",
    "description": "A design-led cameras pick from Leica.",
    "image": "",
    "affiliateUrl": "https://leica-camera.com/en-US/photography/cameras/q/q3-black",
    "amazonUrl": "https://www.amazon.com/s?k=Leica+Leica+Q3",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Leica+Leica+Q3",
    "price": "$6,735",
    "startingVotes": 847
  },
  {
    "id": "rimowa-classic-cabin",
    "name": "Classic Cabin",
    "brand": "Rimowa",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Rimowa.",
    "image": "",
    "affiliateUrl": "https://www.rimowa.com/us/en/luggage/colour/silver/cabin/97353004.html",
    "amazonUrl": "https://www.amazon.com/s?k=Rimowa+Classic+Cabin",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Rimowa+Classic+Cabin",
    "price": "$1,600",
    "startingVotes": 840
  },
  {
    "id": "humans-since-1982-clockclock-24",
    "name": "ClockClock 24",
    "brand": "Humans Since 1982",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Humans Since 1982.",
    "image": "",
    "affiliateUrl": "https://www.humanssince1982.com/clockclock-24",
    "amazonUrl": "https://www.amazon.com/s?k=Humans+Since+1982+ClockClock+24",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Humans+Since+1982+ClockClock+24",
    "price": "$8,500",
    "startingVotes": 833
  },
  {
    "id": "crushgrind-p-1-pepper-mill",
    "name": "P–1 Pepper Mill",
    "brand": "CrushGrind",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from CrushGrind.",
    "image": "",
    "affiliateUrl": "https://www.crushgrind.com/products/p-1-pepper-mill",
    "amazonUrl": "https://www.amazon.com/s?k=CrushGrind+P%E2%80%931+Pepper+Mill",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=CrushGrind+P%E2%80%931+Pepper+Mill",
    "price": "$299",
    "startingVotes": 826
  },
  {
    "id": "b-ng-l-p-small-square-in-orange-acrylic",
    "name": "Lớp small square in orange acrylic",
    "brand": "BằNG",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from BằNG.",
    "image": "",
    "affiliateUrl": "https://www.bang-studio.com/",
    "amazonUrl": "https://www.amazon.com/s?k=B%E1%BA%B1NG+L%E1%BB%9Bp+small+square+in+orange+acrylic",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=B%E1%BA%B1NG+L%E1%BB%9Bp+small+square+in+orange+acrylic",
    "price": "$195",
    "startingVotes": 819
  },
  {
    "id": "herman-miller-noguchi-coffee-table",
    "name": "Noguchi Coffee Table",
    "brand": "Herman Miller",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Herman Miller.",
    "image": "",
    "affiliateUrl": "https://store.hermanmiller.com/living-room-furniture-side-tables/noguchi-table/100104469.html",
    "amazonUrl": "https://www.amazon.com/s?k=Herman+Miller+Noguchi+Coffee+Table",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Herman+Miller+Noguchi+Coffee+Table",
    "price": "$2,745",
    "startingVotes": 812
  },
  {
    "id": "breda-pulse-tandem",
    "name": "Pulse (Tandem)",
    "brand": "Breda",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Breda.",
    "image": "",
    "affiliateUrl": "https://www.breda.com/products/pulse-tandem",
    "amazonUrl": "https://www.amazon.com/s?k=Breda+Pulse+%28Tandem%29",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Breda+Pulse+%28Tandem%29",
    "price": "$230",
    "startingVotes": 805
  },
  {
    "id": "nothing-ear-3",
    "name": "Ear (3)",
    "brand": "Nothing",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Nothing.",
    "image": "",
    "affiliateUrl": "https://nothing.tech/products/ear-3",
    "amazonUrl": "https://www.amazon.com/s?k=Nothing+Ear+%283%29",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Nothing+Ear+%283%29",
    "price": "$149",
    "startingVotes": 798
  },
  {
    "id": "aulumu-m01-4-in-1-folding-wireless-charging-station-pad",
    "name": "M01 4-in-1 Folding Wireless Charging Station & Pad",
    "brand": "Aulumu",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Aulumu.",
    "image": "",
    "affiliateUrl": "https://aulumu.com/products/m01-4-in-1-folding-wireless-charging-station-pad",
    "amazonUrl": "https://www.amazon.com/s?k=Aulumu+M01+4-in-1+Folding+Wireless+Charging+Station+%26+Pad",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Aulumu+M01+4-in-1+Folding+Wireless+Charging+Station+%26+Pad",
    "price": "$109",
    "startingVotes": 791
  },
  {
    "id": "la-marzocco-linea-micra",
    "name": "Linea Micra",
    "brand": "La Marzocco",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from La Marzocco.",
    "image": "",
    "affiliateUrl": "https://lamarzocco.com/us/en/home-products/espresso-machines/linea-micra/",
    "amazonUrl": "https://www.amazon.com/s?k=La+Marzocco+Linea+Micra",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=La+Marzocco+Linea+Micra",
    "price": "$4,500",
    "startingVotes": 784
  },
  {
    "id": "subminimal-subscale",
    "name": "Subscale",
    "brand": "Subminimal",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Subminimal.",
    "image": "",
    "affiliateUrl": "https://subminimal.com/products/subscale",
    "amazonUrl": "https://www.amazon.com/s?k=Subminimal+Subscale",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Subminimal+Subscale",
    "price": "$50",
    "startingVotes": 777
  },
  {
    "id": "sony-wh-1000-xm6",
    "name": "WH-1000 XM6",
    "brand": "Sony",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Sony.",
    "image": "",
    "affiliateUrl": "https://electronics.sony.com/audio/headphones/headband/p/wh1000xm6-b",
    "amazonUrl": "https://www.amazon.com/s?k=Sony+WH-1000+XM6",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Sony+WH-1000+XM6",
    "price": "$400",
    "startingVotes": 770
  },
  {
    "id": "nintendo-switch-2",
    "name": "Switch 2",
    "brand": "Nintendo",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Nintendo.",
    "image": "",
    "affiliateUrl": "https://www.nintendo.com/us/gaming-systems/switch-2/",
    "amazonUrl": "https://www.amazon.com/s?k=Nintendo+Switch+2",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Nintendo+Switch+2",
    "price": "$450",
    "startingVotes": 763
  },
  {
    "id": "phaidon-the-design-book",
    "name": "The Design Book",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "",
    "affiliateUrl": "https://www.phaidon.com/store/design/the-design-book-9781838661433/",
    "amazonUrl": "https://www.amazon.com/s?k=Phaidon+The+Design+Book",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Phaidon+The+Design+Book",
    "price": "$18",
    "startingVotes": 756
  },
  {
    "id": "xbloom-xbloom-studio-coffee-machine",
    "name": "xBloom Studio Coffee Machine",
    "brand": "xBloom",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from xBloom.",
    "image": "",
    "affiliateUrl": "https://xbloom.com/products/xbloom-studio",
    "amazonUrl": "https://www.amazon.com/s?k=xBloom+xBloom+Studio+Coffee+Machine",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=xBloom+xBloom+Studio+Coffee+Machine",
    "price": "$599",
    "startingVotes": 749
  },
  {
    "id": "apple-iphone-17-pro",
    "name": "iPhone 17 Pro",
    "brand": "Apple",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Apple.",
    "image": "",
    "affiliateUrl": "https://www.apple.com/iphone/",
    "amazonUrl": "https://www.amazon.com/s?k=Apple+iPhone+17+Pro",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Apple+iPhone+17+Pro",
    "price": "$1,099",
    "startingVotes": 742
  },
  {
    "id": "serica-ref-1174-1-parade",
    "name": "Ref. 1174-1 Parade",
    "brand": "Serica",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Serica.",
    "image": "",
    "affiliateUrl": "https://www.serica-watches.com/en/product/1174-parade/",
    "amazonUrl": "https://www.amazon.com/s?k=Serica+Ref.+1174-1+Parade",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Serica+Ref.+1174-1+Parade",
    "price": "$1,490",
    "startingVotes": 735
  },
  {
    "id": "ligne-roset-togo-loveseat",
    "name": "Togo ® Loveseat",
    "brand": "Ligne Roset",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Ligne Roset.",
    "image": "",
    "affiliateUrl": "https://www.ligne-roset.com/us/modele/living/sofas/togo/2602",
    "amazonUrl": "https://www.amazon.com/s?k=Ligne+Roset+Togo+%C2%AE+Loveseat",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Ligne+Roset+Togo+%C2%AE+Loveseat",
    "price": "$6,575",
    "startingVotes": 728
  },
  {
    "id": "dyson-solarcycle-morph-floor",
    "name": "Solarcycle Morph Floor",
    "brand": "Dyson",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Dyson.",
    "image": "",
    "affiliateUrl": "https://www.dyson.com/lighting/floor-lamps/solarcycle-morph",
    "amazonUrl": "https://www.amazon.com/s?k=Dyson+Solarcycle+Morph+Floor",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Dyson+Solarcycle+Morph+Floor",
    "price": "$849",
    "startingVotes": 721
  },
  {
    "id": "grau-salt",
    "name": "Salt",
    "brand": "Grau",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Grau.",
    "image": "",
    "affiliateUrl": "https://www.grau.art/en/products/salt",
    "amazonUrl": "https://www.amazon.com/s?k=Grau+Salt",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Grau+Salt",
    "price": "$503",
    "startingVotes": 714
  },
  {
    "id": "jbl-flip-6-portable-bluetooth-speaker",
    "name": "Flip 6 Portable Bluetooth Speaker",
    "brand": "JBL",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from JBL.",
    "image": "",
    "affiliateUrl": "https://www.jbl.com/bluetooth-speakers/JBLFLIP6BLKAM.html",
    "amazonUrl": "https://www.amazon.com/s?k=JBL+Flip+6+Portable+Bluetooth+Speaker",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=JBL+Flip+6+Portable+Bluetooth+Speaker",
    "price": "$130",
    "startingVotes": 707
  },
  {
    "id": "snow-peak-titanium-spork",
    "name": "Titanium Spork",
    "brand": "Snow Peak",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Snow Peak.",
    "image": "",
    "affiliateUrl": "https://www.snowpeak.com/products/titanium-spork",
    "amazonUrl": "https://www.amazon.com/s?k=Snow+Peak+Titanium+Spork",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Snow+Peak+Titanium+Spork",
    "price": "$10",
    "startingVotes": 700
  },
  {
    "id": "standards-manual-parks-united-states-national-park-service-maps",
    "name": "Parks: United States National Park Service Maps",
    "brand": "Standards Manual",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Standards Manual.",
    "image": "",
    "affiliateUrl": "https://standardsmanual.com/products/parks",
    "amazonUrl": "https://www.amazon.com/s?k=Standards+Manual+Parks%3A+United+States+National+Park+Service+Maps",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Standards+Manual+Parks%3A+United+States+National+Park+Service+Maps",
    "price": "$40",
    "startingVotes": 693
  },
  {
    "id": "hoto-camplight-rechargeable-led-camping-lantern",
    "name": "CampLight Rechargeable LED Camping Lantern",
    "brand": "Hoto",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Hoto.",
    "image": "",
    "affiliateUrl": "https://hototools.com/products/camplight-rechargeable-led-camping-lantern",
    "amazonUrl": "https://www.amazon.com/s?k=Hoto+CampLight+Rechargeable+LED+Camping+Lantern",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Hoto+CampLight+Rechargeable+LED+Camping+Lantern",
    "price": "$60",
    "startingVotes": 686
  },
  {
    "id": "anker-solix-everfrost-2-electric-cooler",
    "name": "SOLIX EverFrost 2 Electric Cooler",
    "brand": "Anker",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Anker.",
    "image": "",
    "affiliateUrl": "https://www.anker.com/products/a17b3",
    "amazonUrl": "https://www.amazon.com/s?k=Anker+SOLIX+EverFrost+2+Electric+Cooler",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Anker+SOLIX+EverFrost+2+Electric+Cooler",
    "price": "$700",
    "startingVotes": 679
  },
  {
    "id": "snow-peak-rechargeable-mini-hozuki-lantern",
    "name": "Rechargeable Mini Hozuki Lantern",
    "brand": "Snow Peak",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Snow Peak.",
    "image": "",
    "affiliateUrl": "https://www.snowpeak.com/products/rechargeable-mini-hozuki",
    "amazonUrl": "https://www.amazon.com/s?k=Snow+Peak+Rechargeable+Mini+Hozuki+Lantern",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Snow+Peak+Rechargeable+Mini+Hozuki+Lantern",
    "price": "$70",
    "startingVotes": 672
  },
  {
    "id": "wacaco-minipresso-gr2-espresso-machine",
    "name": "Minipresso GR2 Espresso Machine",
    "brand": "Wacaco",
    "category": "Coffee",
    "tag": "Curated pick",
    "description": "A design-led coffee pick from Wacaco.",
    "image": "",
    "affiliateUrl": "https://www.wacaco.com/products/minipresso-gr2",
    "amazonUrl": "https://www.amazon.com/s?k=Wacaco+Minipresso+GR2+Espresso+Machine",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Wacaco+Minipresso+GR2+Espresso+Machine",
    "price": "$60",
    "startingVotes": 665
  },
  {
    "id": "stelton-vacuum-jug",
    "name": "Vacuum Jug",
    "brand": "Stelton",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Stelton.",
    "image": "",
    "affiliateUrl": "https://www.stelton.com/en/products/em77-vacuum-jug",
    "amazonUrl": "https://www.amazon.com/s?k=Stelton+Vacuum+Jug",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Stelton+Vacuum+Jug",
    "price": "$120",
    "startingVotes": 658
  },
  {
    "id": "solo-stove-mesa-tabletop-fire-pit",
    "name": "Mesa Tabletop Fire Pit",
    "brand": "Solo Stove",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Solo Stove.",
    "image": "",
    "affiliateUrl": "https://www.solostove.com/en-us/p/mesa",
    "amazonUrl": "https://www.amazon.com/s?k=Solo+Stove+Mesa+Tabletop+Fire+Pit",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Solo+Stove+Mesa+Tabletop+Fire+Pit",
    "price": "$110",
    "startingVotes": 651
  },
  {
    "id": "outask-telescopic-camping-lantern",
    "name": "Telescopic Camping Lantern",
    "brand": "Outask",
    "category": "Travel",
    "tag": "Curated pick",
    "description": "A design-led travel pick from Outask.",
    "image": "",
    "affiliateUrl": "https://outask-td.com/products/telescopic-lantern",
    "amazonUrl": "https://www.amazon.com/s?k=Outask+Telescopic+Camping+Lantern",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Outask+Telescopic+Camping+Lantern",
    "price": "$150",
    "startingVotes": 644
  },
  {
    "id": "smeg-electric-kettle",
    "name": "Electric Kettle",
    "brand": "Smeg",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Smeg.",
    "image": "",
    "affiliateUrl": "https://www.smeg.com/us/products/KLF03",
    "amazonUrl": "https://www.amazon.com/s?k=Smeg+Electric+Kettle",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Smeg+Electric+Kettle",
    "price": "$275",
    "startingVotes": 637
  },
  {
    "id": "lego-wildflower-bouquet",
    "name": "Wildflower Bouquet",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/product/wildflower-bouquet-10313",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+Wildflower+Bouquet",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+Wildflower+Bouquet",
    "price": "$60",
    "startingVotes": 630
  },
  {
    "id": "le-creuset-signature-round-dutch-oven",
    "name": "Signature Round Dutch Oven",
    "brand": "Le Creuset",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Le Creuset.",
    "image": "",
    "affiliateUrl": "https://www.lecreuset.com/signature-round-dutch-oven/LS2501.html",
    "amazonUrl": "https://www.amazon.com/s?k=Le+Creuset+Signature+Round+Dutch+Oven",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Le+Creuset+Signature+Round+Dutch+Oven",
    "price": "$420",
    "startingVotes": 623
  },
  {
    "id": "gucci-bloom-eau-de-parfum",
    "name": "Bloom Eau De Parfum",
    "brand": "Gucci",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Gucci.",
    "image": "",
    "affiliateUrl": "https://www.gucci.com/us/en/pr/beauty/fragrances/fragrances-for-women/bloom-eau-de-parfum-100ml-p-488830999990099",
    "amazonUrl": "https://www.amazon.com/s?k=Gucci+Bloom+Eau+De+Parfum",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Gucci+Bloom+Eau+De+Parfum",
    "price": "$60",
    "startingVotes": 616
  },
  {
    "id": "aesop-r-zu-eau-de-parfum",
    "name": "Rōzu Eau De Parfum",
    "brand": "Aesop",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Aesop.",
    "image": "",
    "affiliateUrl": "https://www.aesop.com/us/p/fragrance/floral/rozu-eau-de-parfum/",
    "amazonUrl": "https://www.amazon.com/s?k=Aesop+R%C5%8Dzu+Eau+De+Parfum",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Aesop+R%C5%8Dzu+Eau+De+Parfum",
    "price": "$200",
    "startingVotes": 609
  },
  {
    "id": "assouline-mother-and-child-coffee-table-book",
    "name": "Mother And Child Coffee Table Book",
    "brand": "Assouline",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Assouline.",
    "image": "",
    "affiliateUrl": "https://www.assouline.com/products/mother-and-child",
    "amazonUrl": "https://www.amazon.com/s?k=Assouline+Mother+And+Child+Coffee+Table+Book",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Assouline+Mother+And+Child+Coffee+Table+Book",
    "price": "$120",
    "startingVotes": 602
  },
  {
    "id": "phaidon-woman-made-great-women-designers",
    "name": "Woman Made: Great Women Designers",
    "brand": "Phaidon",
    "category": "Books",
    "tag": "Curated pick",
    "description": "A design-led books pick from Phaidon.",
    "image": "",
    "affiliateUrl": "https://www.phaidon.com/store/design/woman-made-great-women-designers-9781838662850/",
    "amazonUrl": "https://www.amazon.com/s?k=Phaidon+Woman+Made%3A+Great+Women+Designers",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Phaidon+Woman+Made%3A+Great+Women+Designers",
    "price": "$60",
    "startingVotes": 595
  },
  {
    "id": "hatch-restore-3-sunrise-alarm-clock",
    "name": "Restore 3 Sunrise Alarm Clock",
    "brand": "Hatch",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Hatch.",
    "image": "",
    "affiliateUrl": "https://www.hatch.co/restore",
    "amazonUrl": "https://www.amazon.com/s?k=Hatch+Restore+3+Sunrise+Alarm+Clock",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Hatch+Restore+3+Sunrise+Alarm+Clock",
    "price": "$170",
    "startingVotes": 588
  },
  {
    "id": "stakt-original-foldable-yoga-mat",
    "name": "Original Foldable Yoga Mat",
    "brand": "Stakt",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Stakt.",
    "image": "",
    "affiliateUrl": "https://staktmat.com/products/the-stakt-mat",
    "amazonUrl": "https://www.amazon.com/s?k=Stakt+Original+Foldable+Yoga+Mat",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Stakt+Original+Foldable+Yoga+Mat",
    "price": "$90",
    "startingVotes": 581
  },
  {
    "id": "gucci-mercato-tote-bag",
    "name": "Mercato Tote Bag",
    "brand": "Gucci",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Gucci.",
    "image": "",
    "affiliateUrl": "https://www.gucci.com/us/en/pr/women/handbags/tote-bags-for-women/mercato-tote-bag-p-815452AAC7L1060",
    "amazonUrl": "https://www.amazon.com/s?k=Gucci+Mercato+Tote+Bag",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Gucci+Mercato+Tote+Bag",
    "price": "$3,600",
    "startingVotes": 574
  },
  {
    "id": "kate-mcleod-sleep-stone-solid-body-moisturizer-starter-kit",
    "name": "Sleep Stone Solid Body Moisturizer Starter Kit",
    "brand": "Kate McLeod",
    "category": "Personal",
    "tag": "Curated pick",
    "description": "A design-led personal pick from Kate McLeod.",
    "image": "",
    "affiliateUrl": "https://www.katemcleod.com/products/sleep-stone",
    "amazonUrl": "https://www.amazon.com/s?k=Kate+McLeod+Sleep+Stone+Solid+Body+Moisturizer+Starter+Kit",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Kate+McLeod+Sleep+Stone+Solid+Body+Moisturizer+Starter+Kit",
    "price": "$45",
    "startingVotes": 567
  },
  {
    "id": "diptyque-baies-scented-candle",
    "name": "Baies Scented Candle",
    "brand": "Diptyque",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Diptyque.",
    "image": "",
    "affiliateUrl": "https://www.diptyqueparis.com/en_us/p/baies-berries-candle.html",
    "amazonUrl": "https://www.amazon.com/s?k=Diptyque+Baies+Scented+Candle",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Diptyque+Baies+Scented+Candle",
    "price": "$70",
    "startingVotes": 560
  },
  {
    "id": "spigen-classic-ls-magfit-case",
    "name": "Classic LS MagFit Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "",
    "affiliateUrl": "https://www.spigen.com/products/iphone-classic-ls-magfit-case",
    "amazonUrl": "https://www.amazon.com/s?k=Spigen+Classic+LS+MagFit+Case",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Spigen+Classic+LS+MagFit+Case",
    "price": "$35",
    "startingVotes": 553
  },
  {
    "id": "wokyis-retro-docking-station-for-mac-mini",
    "name": "Retro Docking Station For Mac Mini",
    "brand": "Wokyis",
    "category": "Workspace",
    "tag": "Curated pick",
    "description": "A design-led workspace pick from Wokyis.",
    "image": "",
    "affiliateUrl": "https://wokyis.com/products/retro-docking-station-for-mac-mini",
    "amazonUrl": "https://www.amazon.com/s?k=Wokyis+Retro+Docking+Station+For+Mac+Mini",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Wokyis+Retro+Docking+Station+For+Mac+Mini",
    "price": "$170",
    "startingVotes": 546
  },
  {
    "id": "spigen-classic-c1-apple-watch-charger-stand",
    "name": "Classic C1 Apple Watch Charger Stand",
    "brand": "Spigen",
    "category": "Watches",
    "tag": "Curated pick",
    "description": "A design-led watches pick from Spigen.",
    "image": "",
    "affiliateUrl": "https://www.spigen.com/products/apple-watch-classic-c1-stand",
    "amazonUrl": "https://www.amazon.com/s?k=Spigen+Classic+C1+Apple+Watch+Charger+Stand",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Spigen+Classic+C1+Apple+Watch+Charger+Stand",
    "price": "$20",
    "startingVotes": 539
  },
  {
    "id": "8bitdo-retro-mechanical-keyboard",
    "name": "Retro Mechanical Keyboard",
    "brand": "8BitDo",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from 8BitDo.",
    "image": "",
    "affiliateUrl": "https://www.8bitdo.com/retro-mechanical-keyboard/",
    "amazonUrl": "https://www.amazon.com/s?k=8BitDo+Retro+Mechanical+Keyboard",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=8BitDo+Retro+Mechanical+Keyboard",
    "price": "$90",
    "startingVotes": 532
  },
  {
    "id": "8bitdo-retro-r8-mouse",
    "name": "Retro R8 Mouse",
    "brand": "8BitDo",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from 8BitDo.",
    "image": "",
    "affiliateUrl": "https://www.8bitdo.com/retro-r8-mouse/",
    "amazonUrl": "https://www.amazon.com/s?k=8BitDo+Retro+R8+Mouse",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=8BitDo+Retro+R8+Mouse",
    "price": "$50",
    "startingVotes": 525
  },
  {
    "id": "spigen-classic-c1-magfit-case",
    "name": "Classic C1 MagFit Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "",
    "affiliateUrl": "https://www.spigen.com/products/iphone-classic-c1-magfit-case",
    "amazonUrl": "https://www.amazon.com/s?k=Spigen+Classic+C1+MagFit+Case",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Spigen+Classic+C1+MagFit+Case",
    "price": "$35",
    "startingVotes": 518
  },
  {
    "id": "spigen-classic-ls-airpods-pro-3-case",
    "name": "Classic LS AirPods Pro 3 Case",
    "brand": "Spigen",
    "category": "Carry",
    "tag": "Curated pick",
    "description": "A design-led carry pick from Spigen.",
    "image": "",
    "affiliateUrl": "https://www.spigen.com/products/airpods-pro-classic-ls-case",
    "amazonUrl": "https://www.amazon.com/s?k=Spigen+Classic+LS+AirPods+Pro+3+Case",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Spigen+Classic+LS+AirPods+Pro+3+Case",
    "price": "$45",
    "startingVotes": 511
  },
  {
    "id": "native-union-pop-phone",
    "name": "Pop Phone",
    "brand": "Native Union",
    "category": "Tech",
    "tag": "Curated pick",
    "description": "A design-led tech pick from Native Union.",
    "image": "",
    "affiliateUrl": "https://www.nativeunion.com/products/pop-phone",
    "amazonUrl": "https://www.amazon.com/s?k=Native+Union+Pop+Phone",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Native+Union+Pop+Phone",
    "price": "$40",
    "startingVotes": 504
  },
  {
    "id": "foreverspin-stainless-steel-spinning-top",
    "name": "Stainless Steel Spinning Top",
    "brand": "ForeverSpin",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from ForeverSpin.",
    "image": "",
    "affiliateUrl": "https://foreverspin.com/products/stainless-steel-spinning-top",
    "amazonUrl": "https://www.amazon.com/s?k=ForeverSpin+Stainless+Steel+Spinning+Top",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=ForeverSpin+Stainless+Steel+Spinning+Top",
    "price": "$47",
    "startingVotes": 497
  },
  {
    "id": "lego-ferrari-f40-10248",
    "name": "Ferrari F40 10248",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/search?q=Ferrari%20F40",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+Ferrari+F40+10248",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+Ferrari+F40+10248",
    "price": "$25",
    "startingVotes": 490
  },
  {
    "id": "printworks-art-of-chess-set",
    "name": "Art of Chess Set",
    "brand": "Printworks",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Printworks.",
    "image": "",
    "affiliateUrl": "https://printworksmarket.com/products/art-of-chess",
    "amazonUrl": "https://www.amazon.com/s?k=Printworks+Art+of+Chess+Set",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Printworks+Art+of+Chess+Set",
    "price": "$60",
    "startingVotes": 483
  },
  {
    "id": "the-serious-toy-company-tyrannosaurus",
    "name": "Tyrannosaurus",
    "brand": "The Serious Toy Company",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from The Serious Toy Company.",
    "image": "",
    "affiliateUrl": "https://theserioustoycompany.com/",
    "amazonUrl": "https://www.amazon.com/s?k=The+Serious+Toy+Company+Tyrannosaurus",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=The+Serious+Toy+Company+Tyrannosaurus",
    "price": "$60",
    "startingVotes": 476
  },
  {
    "id": "lego-fifa-world-cup-official-trophy",
    "name": "FIFA World Cup Official Trophy",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/product/fifa-world-cup-official-trophy-43020",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+FIFA+World+Cup+Official+Trophy",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+FIFA+World+Cup+Official+Trophy",
    "price": "$200",
    "startingVotes": 469
  },
  {
    "id": "lego-game-boy-72046",
    "name": "Game Boy™ 72046",
    "brand": "Lego",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/product/game-boy-72046",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+Game+Boy%E2%84%A2+72046",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+Game+Boy%E2%84%A2+72046",
    "price": "$60",
    "startingVotes": 462
  },
  {
    "id": "cards-against-humanity-international-edition",
    "name": "International Edition",
    "brand": "Cards Against Humanity",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Cards Against Humanity.",
    "image": "",
    "affiliateUrl": "https://www.cardsagainsthumanity.com/products/cards-against-humanity-international-edition",
    "amazonUrl": "https://www.amazon.com/s?k=Cards+Against+Humanity+International+Edition",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Cards+Against+Humanity+International+Edition",
    "price": "$30",
    "startingVotes": 455
  },
  {
    "id": "theory-11-artisan-playing-cards",
    "name": "Artisan Playing Cards",
    "brand": "Theory 11",
    "category": "Lifestyle",
    "tag": "Curated pick",
    "description": "A design-led lifestyle pick from Theory 11.",
    "image": "",
    "affiliateUrl": "https://store.theory11.com/products/artisan",
    "amazonUrl": "https://www.amazon.com/s?k=Theory+11+Artisan+Playing+Cards",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Theory+11+Artisan+Playing+Cards",
    "price": "$20",
    "startingVotes": 448
  },
  {
    "id": "lego-icons-land-rover-classic-defender-90",
    "name": "Icons Land Rover Classic Defender 90",
    "brand": "Lego",
    "category": "Home",
    "tag": "Curated pick",
    "description": "A design-led home pick from Lego.",
    "image": "",
    "affiliateUrl": "https://www.lego.com/en-us/product/land-rover-classic-defender-90-10317",
    "amazonUrl": "https://www.amazon.com/s?k=Lego+Icons+Land+Rover+Classic+Defender+90",
    "ebayUrl": "https://www.ebay.com/sch/i.html?_nkw=Lego+Icons+Land+Rover+Classic+Defender+90",
    "price": "$240",
    "startingVotes": 441
  }
];
